version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      general:
    artifacts:
       - /home/ubuntu/unideal-android/app/build/outputs/apk/
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          
          destination: outputs
      - store_test_results:
          path: app/build/test-results
          test:
    override:
 
      - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-21.1.2,android-21,extra-google-m2repository,extra-google-google_play_services,extra-android-support
      - chmod +x gradlew
      - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
    # start the emulator
      - emulator -avd circleci-android24 -no-window:
          background: true
          parallel: true
    # wait for it to have booted
      - circle-android wait-for-boot
    # run tests  against the emulator.
      - ./gradlew connectedAndroidTest
    # copy the build outputs to artifacts
      - cp -r my-project/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
      - cp -r my-project/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
